<?php
$four = ['Excellent' => 4, 'Good' => 4, 'Fair' => 3, 'Poor' => 2];
$satisfied = ['5 - Very Satisfied' => 5, '4 - Satisfied' => 4, '3 - Neutral' => 3, '2 - Dissatisfied' => 2, '1 - Very Dissatisfied' => 1];
$well = ['5 - Very Well' => 5, '4 - Well' => 4, '3 - Average' => 3, '2 - Poorly' => 2, '1 - Very Poorly' => 1];
$fast = ['5 - Very Fast' => 5, '4 - Fast' => 4, '3 - Average' => 3, '2 - Slow' => 2, '1 - Very Slow' => 1];
$helpful = ['5 - Very Helpful' => 5, '4 - Helpful' => 4, '3 - Neutral' => 3, '2 - Unhelpful' => 2, '1 - Very Unhelpful' => 1];
$accurate = ['5 - Very Accurate' => 5, '4 - Accurate' => 4, '3 - Average' => 3, '2 - Inaccurate' => 2, '1 - Very Inaccurate' => 1];
$safe = ['5 - Very Safe' => 5, '4 - Safe' => 4, '3 - Neutral' => 3, '2 - Unsafe' => 2, '1 - Very Unsafe' => 1];
return [
  'registrar' => ['name' => "Registrar's Office", 'section' => 'Enrollment & Records Service Experience', 'questions' => [['How would you rate your overall enrollment/registration experience?', $four], ['How satisfied are you with the processing time for documents (COR, TOR, etc.)?', $satisfied], ['How accurate were your academic records/documents when released?', $four], ['How responsive was the staff when you raised a concern?', ['5 - Very Responsive'=>5,'4 - Responsive'=>4,'3 - Neutral'=>3,'2 - Unresponsive'=>2,'1 - Very Unresponsive'=>1]]]],
  'guidance' => ['name' => 'Guidance Office', 'section' => 'Counseling & Student Welfare Experience', 'questions' => [['How would you rate the approachability of the guidance staff?', $four], ['How well did the guidance office address your personal/academic concern?', $well], ['How comfortable did you feel discussing your concerns with the office?', ['5 - Very Comfortable'=>5,'4 - Comfortable'=>4,'3 - Neutral'=>3,'2 - Uncomfortable'=>2,'1 - Very Uncomfortable'=>1]], ['How satisfied are you with the confidentiality of your session/records?', $satisfied]]],
  'clinic' => ['name' => 'Clinic Office', 'section' => 'Health Service Experience', 'questions' => [['How would you rate the quality of care you received?', $four], ['How quickly were you attended to during your visit?', $fast], ['How satisfied are you with the availability of medicines/first-aid supplies?', $satisfied], ['How would you rate the cleanliness and comfort of the clinic facility?', $four]]],
  'accounting' => ['name' => 'Accounting Office', 'section' => 'Payment & Billing Experience', 'questions' => [['How clear were your billing statements/fee breakdowns?', $four], ["How satisfied are you with the staff's assistance in resolving payment issues?", $satisfied], ['How would you rate the waiting time when transacting with this office?', $four], ['How accurate were your payment records/receipts?', $accurate]]],
  'student-organizations' => ['name' => 'Office of Student Organizations (PSSC / College Organizations)', 'section' => 'Student Organization Support Experience', 'questions' => [["How would you rate the office's support for your organization's activities?", $four], ['How satisfied are you with the communication regarding org requirements/events?', $satisfied], ['How well are concerns raised through your organization addressed?', $well], ['How would you rate the accessibility of the office for org-related transactions?', $four]]],
  'security' => ['name' => 'Security Office', 'section' => 'Campus Safety & Security Experience', 'questions' => [['How safe do you feel on campus due to the presence of security personnel?', $safe], ["How would you rate the security staff's response to concerns/incidents?", $four], ['How satisfied are you with the ID-checking/entry process at campus gates?', $satisfied], ['How professional and approachable are the security personnel?', $four]]],
  'mis' => ['name' => 'Management Information Systems (MIS) Office', 'section' => 'Technical/System Support Experience', 'questions' => [["How would you rate the reliability of the school's online systems/portals?", $four], ['How satisfied are you with the resolution time for technical concerns?', $satisfied], ['How helpful was the MIS staff when you needed technical assistance?', $helpful], ['How would you rate the accessibility/usability of MIS-managed platforms?', $four]]],
  'admission' => ['name' => 'Admission Services Office', 'section' => 'Admission Process Experience', 'questions' => [['How would you rate the clarity of the admission requirements/instructions?', $four], ['How satisfied are you with the processing time of your admission/application?', $satisfied], ['How helpful was the staff during your admission process?', $helpful], ['How well were your admission-related concerns addressed?', $four]]],
  'student-services' => ['name' => 'Student Services Office (SSO)', 'section' => 'General Student Services Experience', 'questions' => [['How would you rate the overall support provided by the Student Services Office?', $four], ['How satisfied are you with how your concerns were addressed?', $satisfied], ['How accessible is the office when you need assistance?', ['5 - Very Accessible'=>5,'4 - Accessible'=>4,'3 - Average'=>3,'2 - Inaccessible'=>2,'1 - Very Inaccessible'=>1]], ['How would you rate the courtesy and professionalism of the staff?', $four]]],
  'vp-administration-finance' => ['name' => 'Office of the Vice President for Administration and Finance', 'section' => 'Administrative & Financial Service Experience', 'questions' => [['How would you rate the transparency of financial transactions overseen by this office (e.g., fees, subsidies)?', $four], ['How satisfied are you with the efficiency of administrative processes managed by this office?', $satisfied], ['How well does the office communicate updates on administrative/financial policies affecting students?', $well], ['How would you rate the office’s responsiveness to concerns related to administrative or financial matters?', $four]]],
  'utility' => ['name' => 'Utility Office', 'section' => 'Campus Facilities & Utility Maintenance Experience', 'questions' => [['How would you rate the cleanliness and maintenance of campus facilities (classrooms, comfort rooms, hallways)?', $four], ['How satisfied are you with the response time for maintenance/repair requests (e.g., broken chairs, aircon, plumbing)?', $satisfied], ['How reliable are the campus utilities (electricity, water, internet connectivity in common areas)?', ['5 - Very Reliable'=>5,'4 - Reliable'=>4,'3 - Average'=>3,'2 - Unreliable'=>2,'1 - Very Unreliable'=>1]], ['How would you rate the overall safety and functionality of campus facilities maintained by the Utility Office?', $four]]],
];
